-- +goose Up
-- +goose StatementBegin
CREATE TABLE store_images (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path varchar(512) NOT NULL,
    item_id int NOT NULL REFERENCES store_items(id) ON DELETE CASCADE
);
CREATE INDEX store_images_item_id ON store_images (item_id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX store_images_item_id;
DROP TABLE store_images;
-- +goose StatementEnd
