name: Store Backend PR checks
on:
  pull_request:
    paths:
      - 'src/store-backend/**'
jobs:
  lint:
    uses: ./.github/workflows/backend-golangci-lint.yaml
  container-image:
    uses: ./.github/workflows/backend-image.yaml
    with:
      tag: "store_backend:snapshot-${{github.event.pull_request.number}}-${{github.env.GITHUB_SHA}}"
