---
name: "Backend -- GolangCI lint"
on:
  workflow_call: {}
jobs:
  lint:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'src/store_backend/go.mod'
          cache-dependency-path: 'src/store_backend/go.mod'

      - uses: golangci/golangci-lint-action@v9
        with:
          working-directory: src/store_backend
          version: v2.13.2
